### ISSUE TITLE
Option to set delay for API response

### ISSUE THREAD

**Issue by jeremyschultz** [phstc/putsreq#18]
I had the idea to add a parameter to the URL (or a setting in the admin) so responses could be delayed a specified amount of time. I'm testing an API right now that takes a few seconds to respond and this would be very useful.

**Comment by phstc** [comment]
hey @jeremyschultz 

You can try to `sleep` using the response builder - you can write some JS for that. You can read the interval you want from the URL parameter then in the JS side (response builder) `sleep(param)`.

Does that work for you?

**Comment by phstc** [comment]
But keep in mind that he maximum allowed sleep in the JavaScript would be 2.5 seconds.

https://github.com/phstc/putsreq/blob/3a0ef442b6ebb65e368bb8463e7f2defcfc287d2/app/models/bucket.rb#L85
