### ISSUE TITLE
Problem using custom headers

### ISSUE THREAD

**Issue by typingincolor** [phstc/putsreq#19]
When I use the header `X-TLRG.force-error` it does not appear in the Request Headers list when using putsreq.com

If I run putsreq on my local machine the header does appear in the list. Any idea why there is the difference?

**Comment by phstc** [comment]
hm it seems that Heroku is ignoring your header because of the `.`. Actually probably nginx is the responsible for that: http://nginx.org/en/docs/http/ngx_http_core_module.html#ignore_invalid_headers

Without `.`, it works:

```bash
curl --header "X_TLRG_force_error: 123" http://putsreq.com/tGGIM5y63ZG1CUQmsrnZ
```
