### ISSUE TITLE
Simple response mechanisms

### ISSUE THREAD

**Issue by DennisHeimbigner** [phstc/putsreq#20]
You might consider providing a set of simple responses that
do not require using responsebuilder. Specifically
1. allow automatic response http code: e.g. 200 or 404 or whatever.
2. simple response body text.
You might also allow http: access.

**Comment by phstc** [comment]
Hey @DennisHeimbigner 

Not sure if I could follow your suggestions entirely. Could you give me some examples?

> 1. allow automatic response http code: e.g. 200 or 404 or whatever.
> 2. simple response body text.

How that would be?

> You might also allow http: access.

What do you mean by allowing http access? 

Thanks

**Comment by DennisHeimbigner** [comment]
>> 1. allow automatic response http code: e.g. 200 or 404 or whatever.u
Pn a particular bucket, provide a numeric field that can be filled in
with an http response code. Then when putsreq gets an request on that bucket,
it records the request and then automatically responds with that http response code.

>> You might also allow http: access.
Never mind this, apparently it already does.

=Dennis Heimbigner

**Comment by phstc** [comment]
> Pn a particular bucket, provide a numeric field that can be filled in
with an http response code. Then when putsreq gets an request on that bucket,
it records the request and then automatically responds with that http response code.

Can you just:

```javascript
response.status = STATUS_CODE_YOU_NEED;
```

? 

Not sure if I got your use case, but maybe you can try to make it dynamically using a `request.param` as well:

```javascript
// http://putsreq.com/my-bucket?status_code=202

response.status = request.params.status_code;
```

wdyt?
