### ISSUE TITLE
The server get 503 Application Error

### ISSUE THREAD

**Issue by tnstiger** [phstc/putsreq#27]
Hi Pablo,

It seems to be 503 on http://putsreq.com/.
I have also try to deploy to heroku from the repo, but it's still show application error.
Do I miss something?

**Comment by tnstiger** [comment]
Hi, 

I use heroku radis addon as DB.
And the error log show below:

========================================================
2016-04-23T02:44:56.043166+00:00 app[web.1]: NoMethodError (undefined method `each' for nil:NilClass):
2016-04-23T02:44:56.043166+00:00 app[web.1]:   app/controllers/home_controller.rb:11:in `index'
========================================================

It seems that it has no buckets.
I try to login redis, there are db0 to db15, and all of them seem are empty.

**Comment by phstc** [comment]
@tnstiger Sorry, I couldn't check this issue earlier. Let me know if you still need any help.
