### ISSUE TITLE
400 Error when posting invalid json

### ISSUE THREAD

**Issue by sadortun** [phstc/putsreq#28]
Hi !

When posting invalid JSON while using `application/json` content type, the server refuse the request.

Is it intentional ?  You should probably accept any payload, and if possible display a warning in the UI that the payload is invalid. This way we would be possible to track what went wrong ! 

Thanks!

**Comment by phstc** [comment]
Hi @sadortun 

Sorry for taking ages to get back to you.

If you make a request setting `Content-Type: application/json` and send an invalid content in the request body, PutsReq will return HTTP 400 Bad request, which I believe is the right behavior.
