### ISSUE TITLE
Format application/json responses

### ISSUE THREAD

**Issue by sadortun** [phstc/putsreq#31]
Hi,

It would be nice to have a nice json viewer when displaying responses in `application/json` format.

Thanks,
Samuel

**Comment by phstc** [comment]
@sadortun hm the issue with a nicer viewer is that we would need to make it in HTML, which would turn it into an invalid JSON, the JSON output is for parsing it with other tools.

If you use Chrome, maybe you could leverage this extension https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc, WDYT?

How do you use the JSON output? Is only for visualization purposes or do you parse it with other tools?

**Comment by sadortun** [comment]
Hi  Pablo, 

I agree that the json must rema8n the same, I was referring on how we can present it to the use in the UI.

On the UI, I use my eyes to inspect the JSON.  For example you could  use http://yesmeck.github.io/jquery-jsonview/ to preview the request body.

**Comment by phstc** [comment]
@sadortun you mean when you click on the JSON link? If so, to do any formatting in the UI, we would cause it to not be a valid JSON, because we would need to format it using HTML.

The JSON URL is the same I use for my integration tests and I need to be able to parse its response as a JSON, if we add any formatting, I can't parse it.

Does that make sense?

**Comment by sadortun** [comment]
Here : 
Instead of displaying the `POST Request` in plain text, use  JsonView or an other client side formatter to make it more readable

![image](https://cloud.githubusercontent.com/assets/794449/21821121/54b99034-d740-11e6-9e75-21ea96923b65.png)

**Comment by phstc** [comment]
@sadortun ah, I got confused by https://github.com/phstc/putsbox/issues/8, I thought your asking about this JSON formatting for PutsBox, not PutsReq, my bad.

Seems to be a good idea, I can play with that.

**Comment by sadortun** [comment]
hahahah !  Great !!

**Comment by phstc** [comment]
@sadortun I'm working (WIP) #32 on a formatting enhancement. Could you test it again to see how it looks like for you? Are you also sending `content-type: application/json`? I'm relying on that for formatting.

**Comment by sadortun** [comment]
Yep, working !
