### ISSUE TITLE
Issue when returning JSON Array

### ISSUE THREAD

**Issue by Notifium** [phstc/putsreq#33]
Hi,

Love this service!

However...If I return:

{"test":"test2"}

It works fine. But if I try to return:

[{"test":"test2"}]

I get the following response:

[{"test"=>"test2"}]

(Example request ID: 58ae23a58ac5c9000a35cfca for http://putsreq.com/HXc0i8jgTyyPaFFNCCHf )

Any ideas,

Regards,
Andy

**Comment by Notifium** [comment]
I kind-of resolved it by returning:

{ "data": [{"test":"test2"}]}

However, that shouldn't really be neccessary, I think?

Andy

**Comment by phstc** [comment]
Hi @Notifium 

Thanks for reporting this. It's definitely a bug. It should be fixed by 3fec802ff40c5a3259afc5a1a5fc8d95c16ba58c, could you test it again?
