### ISSUE TITLE
Content-Type unexpected transformation

### ISSUE THREAD

**Issue by fgalan** [phstc/putsreq#35]
I'm the developer of a software ([Orion Context Broker][1]) that as part of its functionality sends notifications in HTTP/HTTPS as the following one (real stuff, not crafted, i.e. copy&pasted from a local netcat):

    POST http://127.0.0.1:9997/notify?entityId=Lamp1
    Fiware-Servicepath: /
    Ngsiv2-Attrsformat: custom
    Content-Length: 24
    X-Auth-Token: 8472e87bf49c4bba11f731aed6ab12a2
    User-Agent: orion/1.9.0 libcurl/7.38.0
    X-Entitytype: Lamp
    Host: 127.0.0.1:9997
    Accept: application/json
    Fiware-Service: formacion
    Content-Type: application/xml
    Fiware-Correlator: 48305f2a-fae2-11e7-ae1b-000c29173617
    
    <battery>-10.2</battery>

I'm testing with [PutsReq][2] but what I get is the following set of headers from PutsReq inspect page:

    {
      "VERSION": "HTTP/1.1",
      "CONNECTION": "close",
      "ACCEPT-ENCODING": "gzip",
      "USER-AGENT": "orion/1.9.0 libcurl/7.38.0",
      "FIWARE-SERVICE": "formacion",
      "FIWARE-SERVICEPATH": "/",
      "X-AUTH-TOKEN": "8472e87bf49c4bba11f731aed6ab12a2",
      "ACCEPT": "application/json",
      "CONTENT-TYPE": "text/plain; charset=utf-8,application/xml",
      "FIWARE-CORRELATOR": "a220284e-fae2-11e7-ae1b-000c29173617",
      "NGSIV2-ATTRSFORMAT": "custom",
      "X-ENTITYTYPE": "Lamp",
      "CONTENT-LENGTH": "24"
    }

All seems to be ok, except Content-Type, which has changed to the (syntactically wrong): `"text/plain; charset=utf-8,application/xml"` instead of showing what it has received, i.e. `"application/xml"`.

It seems that PutsReq is not showing Content-Type header its receives. Is this a normal PutsReq behaviour? Is a bug?

(`Fiware-Correlator` is unique per HTTP request so it is normal it changes)

  [1]: http://github.com/telefonicaid/fiware-orion
  [2]: https://putsreq.com/

**Comment by fgalan** [comment]
This question has been asked also at https://stackoverflow.com/questions/48287093/do-putsreq-transform-content-type-of-the-requests-it-receives. Not sure which platform is better for this kind of issue but, anyway, sorry for the duplication if that is a problem.

**Comment by phstc** [comment]
Hi @fgalan 

I tried this

```shell
curl -X POST --header "Content-Type: text/xml" -d '<battery>-10.2</battery>' https://putsreq.com/qwDed0vYREZr81JqjtwP
```

And it seems to be working:

![image](https://user-images.githubusercontent.com/105652/35010312-77f0ffba-fad0-11e7-90a4-15420c7ecfc3.png)

Could you try it with a `cURL`?

**Comment by fgalan** [comment]
Seems to be ok. Request:

```
curl -X POST --header "Content-Type: application/xml" -d '<battery>-10.2</battery>' https://putsreq.com/g5tfKD61bkhKsMtZed1t
```

![imagen](https://user-images.githubusercontent.com/1534240/35010800-6a87fff2-fb04-11e7-9958-0d323f6c04c8.png)

Maybe is due to the existence of other headers? I'll try to reproduce with a more complex curl command, trying to mimic the notification that my software is generating. I'll publish the result in a new comment.

Thanks!

**Comment by fgalan** [comment]
I'm unable to reproduce it :) Please close the issue is you want (or leave it opened if you prefer to have it as "reminder"). Thanks so much!
