### ISSUE TITLE
request.params return {} 

### ISSUE THREAD

**Issue by mauroarisci** [phstc/putsreq#36]
return.params always returns {}
example: https://putsreq.com/TOKEN?parameter=123456
therefore:
```
var msg = request.params;
response.body = msg;
```
but I always get empty {}

**Comment by phstc** [comment]
@mauroarisci great catch. It's probably because of the last rack bump. Should be working now. If you use https://putsreq.com/TOKEN?name=123456

Could you double check it?

**Comment by mauroarisci** [comment]
@phstc thanks! I do a triple check willingly, now it's perfect it works well.
https://putsreq.com/TOKEN?parameter=123456
request.params WORK
request.params.name WORK

While for the return in JSON, with a writing of this type:
response.body = {'params': request.params.name};

is it expected to return an html with <div id = Json> ... </ div> right?
I expected (and preferred) a classic XML format.

**Comment by phstc** [comment]
@mauroarisci thanks for checking it. Could you send me your bucket link, so I can check your response builder?


That should return a JSON like in here https://putsreq.com/TOKEN?name=123456

**Comment by phstc** [comment]
![image](https://user-images.githubusercontent.com/105652/35754050-0d7b45ba-0830-11e8-8f38-00e816276406.png)

**Comment by mauroarisci** [comment]
ok ok ok sorry Json it's ok, I have a plugin that injected some code to improve the visualization.
maybe I found another gap, if I want to see the last request via: "/ last"
first -> https://putsreq.com/TOKEN?test=123456
after -> https://putsreq.com/TOKEN/last
I get an empty page.

**Comment by phstc** [comment]
@mauroarisci it's because your last request had an empty body, so `/last` returns an empty body.

**Comment by mauroarisci** [comment]
@phstc ok then / last handles all the POST request methods but does not see the GET type. I got it. Thank you.
