### ISSUE TITLE
Putsreq down?

### ISSUE THREAD

**Issue by MariusJorgensen** [phstc/putsreq#37]
Hi,

It seems like Putsreq is down. I'm just seeing the standard Heroku error page.

![screen shot 2018-03-28 at 14 45 17](https://user-images.githubusercontent.com/20817845/38032923-ab32f902-3296-11e8-86b2-1d9ff09d2e4b.png)

**Comment by phstc** [comment]
@MariusJorgensen thanks for reporting it. Heroku is giving me a lot of `Request timeout`. I need to troubleshoot this.

**Comment by phstc** [comment]
It should be back now.

**Comment by MariusJorgensen** [comment]
Sweet! Just wanted to let you know 👍

**Comment by andreasmartin** [comment]
There seems to be still an issue:

![2018-03-29_13h46_49](https://user-images.githubusercontent.com/4495809/38087232-a4555cd0-3357-11e8-902c-8a194920dfe9.png)

**Comment by phstc** [comment]
hi @andreasmartin 

It's still opening for me. Could you try it again? If it isn't working for you, could you send me the link of your bucket?

**Comment by andreasmartin** [comment]
Hi @phstc 

I just created a fresh bucket and used the following cURL in Postman:
```Bash
curl -i -X POST -d 'name=Pablo' https://putsreq.com/OWz4GaMeFIJztEMpvXQA
```

**Comment by phstc** [comment]
@andreasmartin it's working again. It's something going on with MongoDB and TTL, it isn't expiring records, and MongoLab is returning quote over exceeded.

**Comment by sadortun** [comment]
Was working yesturday, but today, its dead 😢

**Comment by phstc** [comment]
Hi @sadortun 

it is back now. It got too much traffic...

Thanks for reporting it.

**Comment by phstc** [comment]
> it is back now

@sadortun I have to take that back, it is still facing problem. I need to dig more into it. I will keep you posted.
