### ISSUE TITLE
Putsreq is down : Application Error

### ISSUE THREAD

**Issue by jmcaudron** [phstc/putsreq#42]
![capture](https://user-images.githubusercontent.com/15669145/45543725-8e898000-b815-11e8-88b6-e91c6fbcf0c5.JPG)

**Comment by LoiIver** [comment]
and again it's down (((

**Comment by phstc** [comment]
Hi @LoiIver 

Thanks for reporting it. 

PutsReq is back.

**Comment by hchuphal** [comment]
It's down again. Keeps going down.

**Comment by phstc** [comment]
@hchuphal thanks for reporting that. 

I've just limited the number of requests per minute to prevent single users overloading PutsReq's  capacity. 

I hope this helps! 🙏 

I really wanted to keep it more flexible. But it seems there are some users using it with a loop on :/
