### ISSUE TITLE
allow changing of rate limit

### ISSUE THREAD

**Issue by ddavtian** [phstc/putsreq#50]
@phstc possible to allow the user to set the desired rate limit. Looking in the code it seems to be hard coded at the moment. Perhaps this could be read from a config file or at the least ENV var. Thank you!

https://github.com/phstc/putsreq/blob/02505af70def15bd3f232bcad5c30db4d37a1212/config/initializers/rack_attack.rb#L5

**Comment by phstc** [comment]
@ddavtian are you asking for your local setup? If so, maybe a flag (ENV variable) for disabling it entirely instead.

**Comment by ddavtian** [comment]
@phstc yes local setup.

**Comment by phstc** [comment]
@ddavtian makes sense. I disabled throttling by default. From now on, you must set `ENABLE_THROTTLE=true` to enable it back.
