### ISSUE TITLE
Add last_header page

### ISSUE THREAD

**Issue by crfnunes** [phstc/putsreq#56]
Is possible to add a 'last_header' page to return the last header received?

Thank you!

**Comment by phstc** [comment]
Hi @crfnunes 

How would consume the last header?  You can get the last request as JSON https://putsreq.com/your-bucket/last.json and read the property header if you are consuming programatically.

**Comment by crfnunes** [comment]
Hi,

Yes, this is perfect... thank you for your work, great tool!!
