### ISSUE TITLE
Is it possible to call request.forwardTo twice? 

### ISSUE THREAD

**Issue by ClemensGruber** [phstc/putsreq#71]
Many thanks, Pablo for developing PutsReq! It helps a lot to re-write e.g. TTN payloads for different APIs! Today we tried to send data that arrives at PutsReq to two different Servers / APIs in one Response Builder. But we struggled! Seems it is not possible to call `request.forwardTo` twice? 

We did this here:

```
const input   = JSON.parse(request.body);

// -----
// B O B
// -----

const payload_ttn = input.payload_fields;

var output_bob   = {};

[doing cool stuff here]

request.body = output_bob;
request.forwardTo = 'https://example-server-1.org';

// ---------------
// H I V E E Y E S
// ---------------

var output_swarm = {};

[doing other cool stuff here]

const URL = "https://example-server-2.org/api/" + input.dev_id.replace(/-/g, '/') + "/data";

request.body = output_swarm;
request.forwardTo = URL;

```

Do you have a hint how we can realize to send different re-written data structurs to two different endpoints with PutsReq? Is it not possible by design or do we miss something or our syntax is wrong?

**Comment by phstc** [comment]
@ClemensGruber I'm happy you find it useful 🤜 

Double-checking the code, it is by design. I didn't have a fan-out use-case when I developed it.

In the way it is implemented, potentially we could add `request.addForwardTo`, so we could call fan-out to multiple endpoints, but it wouldn't work as procedural as you might need. 

_do this, send forward (a), do that, send forward (b)_, in reality, it would more like _do this, do that send forward (a), send forward (b)._

**Comment by ClemensGruber** [comment]
For our corrent use case the data manipulation and sending to endpoint a and b is independent. So it doesn't matter if we prepare request.body a first and then b or vice versa. But we have different request.bodys not only two different endpoints with the same content. 

So it would be compute output_a, compute output_b and then forward output_a to URL_a and  forward output_b to URL_b? That would help us!

**Comment by phstc** [comment]
Right, that's exactly what I think that wouldn't work. 

Forward URL_a and URL_b, would end up getting the same body, the last computed one.

**Comment by phstc** [comment]
I can give you some guidance in the code if you are interested in sending a pull request. 

This to clarify, [`ForwardRequest`](https://github.com/phstc/putsreq/blob/ce1450373611697f4e054daae7f019cd01a78a79/app/interactors/record_request.rb#L4) is called after the Javascript was computed, so when it gets in the forwarding phrase, it would use the latest `body`.

If you are looking for a more-production-ready solution, maybe AWS SNS fanout or Lambdas could give support for what you need.

**Comment by ClemensGruber** [comment]
Hi Pablo, again thanks for your support and hints. We did some more investigations and found an other way to realize the job sending sending TTN payloads to two different APIs. We set now the switch point a step before PutsReq and send the data twice with two HTTP integrations to different PutsReq pages. So all can be the same on the PutsReq side and we do not need to enlarge things here.
